name: cargo outdated

on:
  workflow_dispatch:
  push:    
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0/12 * * *'
env:
  CARGO_TERM_COLOR: always

jobs:
  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo outdated
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: masinc/cargo-outdated-action@main
